version: "3.8"

services: 
  ntux-backend:
    image: node:13.12.0-alpine
    container_name: ntux-backend
    working_dir: /app
    command: sh -c "yarn && npm run build && npm start"
    ports:
      - 3001:3000
    volumes: 
      - .:/app
 